#! /bin/sh
# /etc/init.d/spiservice 

### BEGIN INIT INFO
# Provides:          spiservice
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start spiservice
# Description:       Start spiservice script.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting spiservice"
    # run application you want to start
    bash /home/pi/spi/spi-boot.sh
    ;;
  stop)
    echo "Stopping noip"
    # kill application you want to stop
    #killall noip2
    ;;
  *)
    echo "Usage: /etc/init.d/spiservice {start|stop}"
    exit 1
    ;;
esac

exit 0